name: simple_logger
description: >-
  Provides super simple APIs for logging. The log also includes called location by setting
  stacktraceEnabled to true. On Android Studio, jump to called location by clicking the log.
version: 0.3.0
author: Masayuki Ono <mono0926@gmail.com>
homepage: https://github.com/mono0926/simple_logger
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  logging: ^0.11.3
  stack_trace: ^1.9.3
dev_dependencies:
  test: ^1.0.0
